name: Sync Zlibrary.py monthly

on:
  schedule:
    - cron: '0 0 1 * *'   # 每月1号0点（UTC）自动运行
  workflow_dispatch:      # 支持手动触发

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download latest Zlibrary.py from bipinkrish/Zlibrary-API
        run: |
          curl -L -o Zlibrary.py https://raw.githubusercontent.com/bipinkrish/Zlibrary-API/main/Zlibrary.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Zlibrary.py
          git commit -m "chore: monthly sync Zlibrary.py from bipinkrish/Zlibrary-API" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
